### ISSUE TITLE
Possible timing attack in new verifyAud

### ISSUE THREAD

**Issue by ngunia** [form3tech-oss/jwt-go#6]
I found this repo since [vault](https://github.com/hashicorp/vault) is using this fork to fix [CVE-2020-26160](https://nvd.nist.gov/vuln/detail/CVE-2020-26160#vulnCurrentDescriptionTitle).

I'm not well versed enough in the JWT spec to know the specific timing attack protection provided `ConstantTimeCompare` [here](https://github.com/form3tech-oss/jwt-go/blob/master/claims.go#L98) is in the first place, but returning on first match introduces a new timing attack. You could theoretically re-arrange the `[]aud` with each value in the slice in the first entry and see which is fastest to determine the desired audience.

I think something as simple as introducing a boolean to track the status and checking every value should fix it:

```go
var validAud bool
for _, a := range aud {
  if subtle.ConstantTimeCompare([]byte(a), []byte(cmp)) != 0 {
    validAud = true
  }
}
return validAud
```

I suppose it could be argued that if you're able to brute force audiences, you could just pass in strings or 1-length string slices until you find the right one too. Again, I'm ignorant as to why there is a constant time comparison in the first place, but I thought it'd at least be worth pointing out.

**Comment by ngunia** [comment]
Actually, I see now. The constant time comparison is to prevent revealing the value of the audience with an incremental brute force. A fast return shouldn't make a difference if all values in `aud` are bad.

**Comment by PawelSmorczewskiSopraSteria** [comment]
@ngunia I am not really experienced here in security also, but wondering... What if I temper token with additional audience values. During validating audience server will not throw an audience error, since its working with first match. So I will have no possibility to inform that something went wrong particularly with audience. I will be only able to return tak signature doesnt match.
Shouldn't we then check all values existing in aud claim?

**Comment by PawelSmorczewskiSopraSteria** [comment]
aaa
